server {
	listen 127.0.0.1:5050;

	root www/html/;

	#error_page 400 /errors/404.html;
}

server {
	listen 127.0.0.1:8080;
	listen 127.0.0.1:4242;
	listen 192.168.1.68:1025;
	listen *:2222;
	listen localhost:6060;

	#relative path
	root www/;
	autoindex on;
	#index index.html ../../www/html/index.html;

	client_max_body_size 100Mb;

	error_page 400 /errors/400.html;

	# Default route
	location / {
		autoindex on;
		root www/html;
		index index.html;
		allowed_methods GET;
	}

	location /testers {
		root www/testers;
		autoindex on;
	}

	# CGI folder
	location /cgi-bin/ {

		#absolute path
		root www/cgi-bin;

		cgi_extension .py /usr/bin/python3;
		cgi_extension .pl /usr/bin/perl;
		cgi_extension .php /usr/bin/php;
	}

	# File upload example
	location /upload {
		allowed_methods POST;
		upload_store uploads;
	}

	# DELETE example
	location /delete {
		allowed_methods DELETE;
		root www/uploads;
	}

	location /images {
		root www/images;
		autoindex on;
	}

}

