server {
    listen 8080;
    listen 192.168.1.68:8083;
    listen unix:@mytest.sock;
    listen unix:/tmp/test.sock;


    server_name intra_tester;
    root YoupiBanane;
    client_max_body_size    100Mb;

    location / {
        allowed_methods GET;
        root www/html;
        index index.html;
    }

    cgi_extension .bla ./cgi_tester POST;

    location /post_body {
        allowed_methods POST;
        client_max_body_size 100;
    }

    location /directory {
        allowed_methods GET;
        root YoupiBanane/;
        index youpi.bad_extension;
    }

    upload_store uploads_destination;
}