server {
	listen 8085;
	root	www/;

	location / {
		allowed_methods GET;
		#root www/html;
		#index index.html;
	}

	location cgi-bin/ {
		cgi_extension .py /usr/bin/python3;
		cgi_extension .pl /usr/bin/perl;
		cgi_extension .php /usr/bin/php;

		root www/;
	}
	
	index /html/index.html;

	client_max_body_size	100Mb;
}