server {
    listen 8080;
    server_name localhost;
    root /www/html;

    # 1. / -> GET only
    location / {
        allowed_methods GET;
        index index.html;
    }

    # 2. *.bla -> POST only, handled by cgi_test
    location *.bla {
        allowed_methods POST;
        cgi_path /www/cgi-bin/;
    }

    # 3. /post_body -> POST only, max body = 100
    location /post_body {
        allowed_methods POST;
        client_max_body_size 100Mb;
    }

    # 4. /directory/ -> GET, rooted at YoupiBanane
    #    If no file is specified, look for youpi.bad_extension
    location /directory {
        allowed_methods GET;
        root /YoupiBanane;
        index youpi.bad_extension;
    }
}