server {
    listen 8080;
    server_name intra_tester;
    root YoupiBanane;
    client_max_body_size    100Mb;

    # 1. / -> GET only
    location / {
        allowed_methods GET;
        root www/html;
        index index.html;
    }

    cgi_extension .bla ./cgi_tester POST;

    # 3. /post_body -> POST only, max body = 100
    location /post_body {
        allowed_methods POST;
        client_max_body_size 100;
    }

    # 4. /directory/ -> GET, rooted at YoupiBanane
    #    If no file is specified, look for youpi.bad_extension
    location /directory {
        allowed_methods GET;
        root YoupiBanane/;
        index youpi.bad_extension;
    }

    upload_store uploads_destination;
}