server {
	listen 192.178.1.1:4242;
	listen 251.145.8.1;
	listen 443;
	listen *:22;
	listen localhost:5432;
	listen unix:/var/run/nginx.sock;

	server_name myserver.local;

	root www;
	index index.html;

	client_max_body_size 10Mb;

	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	return 300 http://$server_name:443;
	return 300 "this is a text";
	return 301 http://$server_name:443;
	return http://$server_name:80; #default code to 302

	# Default route
	location / {
		try_files $uri $uri/ =404;
		
		#HTTP redirection
		return 303;
	}

	# Static files (HTML, CSS, JS, images)
	location /static/ {
		root www/static;
		autoindex on;
	}

	# CGI for Python
	location /cgi-bin/ {
		root www/cgi-bin;
		cgi_extension .py /usr/bin/python3;
	}

	# CGI for PHP
	location /php/ {
		root www/php;
		cgi_extension .php /usr/bin/php-cgi;
		#cgi_path ;
	}

	# File upload example
	location /upload {
		allowed_methods POST;
		upload_store uploads;
	}

	# DELETE example
	location /delete {
		allowed_methods DELETE;
		root www/uploads;
	}
}

