server {
	listen 192.178.1.1:4242;
	listen 251.145.8.1;
	listen 443;
	listen *:22;
	listen localhost:5432;
	listen unix:/var/run/nginx.sock;

	server_name myserver.local;

	#relative path
	root www/;
	autoindex off;
	index index.html ../../www/html/index.html;

	client_max_body_size 1Mb;

	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	return 300 http://$server_name:443;
	return 300 "this is a text";

	# Default route
	location / {
		try_files $uri $uri/ =404;

		index another_index.html;
		return 303;
	}

	# Static files (HTML, CSS, JS, images)
	location /static/ {
		return 301 /www/;
		root someshittery;
		autoindex on;
		index static_index.html;
	}

	# CGI for Python and perl
	location /cgi-bin/ {

		#absolute path
		root www/;

		cgi_extension .py /usr/bin/python3;
		cgi_extension .pl /usr/bin/perl;
	}

	# File upload example
	location /upload {
		allowed_methods POST;
		upload_store uploads;
	}

	# DELETE example
	location /delete {
		allowed_methods DELETE;
		root www/uploads;
	}
}

